### ISSUE TITLE
[FR]Os botões de adicionar e remover horas somem quando o timer é iniciado

### ISSUE THREAD

**Issue by fabricio-X** [Srchronotrigger/CaveiraTimer#1]
Eu testei aqui no meu pc e percebi que quando se define uma quantidade de horas e aperta em começar, os botões de adicionar e remover horas somem, o usuário fica somente com a opção de pausar o timer, seria bom poder pausar o timer para adicionar ou remover horas sem ter que fechar o programa, também seria interessante adicionar um botão para resetar o timer completamente. Eu sei que falar assim é fácil e implementar isso talvez não seja tão fácil, mas acho que se o renan tiver muita dificuldade em usar o programa ele vai usar o que ele já usava antes.

https://github.com/Srchronotrigger/CaveiraTimer/assets/75442748/1bee26d1-896d-4525-8fe4-f64505b93d81

**Comment by Srchronotrigger** [comment]
Olá, boa tarde! Na realidade, essa incapacidade de não poder adicionar horas no modo regressivo é proposital, pois a ideia do modo regressivo é de se fazer lives com o tempo já predefinido, como é o caso de lives de 24 horas ou mais, você define quantas horas deseja que sua live tenha e então você starta e ele irá contar regressivamente até 00 : 00 : 00, entretanto ainda sim você consegue manipular as horas ao fechar o programa e alterar o arquivo tempo.txt, sei que é uma maneira menos ortodoxa de se fazer isso, mas como falei não é planejado que o modo regressivo possa ser alterado durante a contagem, diferentemente do modo progressivo que é planejado para live infinita, esse sim você consegue adicionar ou remover horas pelos botões normalmente.

quanto a possibilidade de resetar a contagem, isso também é feito através do arquivo tempo.txt, bastando o apagar e abrir o programa novamente que ele irá tornar a contar do começo, porém é uma possibilidade a se considerar fazer isso através do próprio programa, também andei pensando em algumas ideias como colocar um seletor de cores ou mesmo de fonte para fazer um ajuste fino no chroma key e deixar da melhor maneira possível, infelizmente no momento eu ando um pouco ocupado pra lançar logo uma versão atualizada, mas vou deixar sua sugestão do reset como feature request, quanto a adicionar tempo no modo regressivo provavelmente não irei adicionar botões para isso nesse modo, mas posso pensar em outra maneira que seja pelo próprio programa também, bom de qualquer maneira é isso, agradeço pelas ideias, fique à vontade para comentar algo a mais se desejar.
